#ifndef NETDIAG_TRANSCEIVER_H
#define NETDIAG_TRANSCEIVER_H

#include <stdbool.h>
#include "network.h" /* For ScenarioType */

/**
 * Optical Transceiver Form-Factors based on SFF specifications.
 */
typedef enum {
    TRANSCEIVER_SFP = 0,     /* 1GbE / 2.5GbE SFP */
    TRANSCEIVER_SFP_PLUS,    /* 10GbE SFP+ (SFF-8431/8472) */
    TRANSCEIVER_QSFP28,      /* 100GbE QSFP28 (SFF-8636/8665) */
    TRANSCEIVER_XFP,         /* 10GbE XFP */
    TRANSCEIVER_UNKNOWN
} TransceiverFormFactor;

/**
 * Optical Transceiver Telemetry Structure.
 *
 * Models standard Digital Diagnostic Monitoring (DDM) / Digital Optical Monitoring (DOM)
 * parameters as specified in SFF-8472 (SFP/SFP+) and SFF-8636 (QSFP+ / QSFP28).
 *
 * NOTE: In this version of NetDiag-C, all optical measurements are synthetically
 * generated by the simulation engine and are NOT direct readings from physical
 * I2C/DOM hardware sensors. The architecture provides pluggable hooks for physical
 * I2C bus drivers (e.g. Linux /dev/i2c-* or netlink ethtool optical module EEPROM)
 * in subsequent hardware integration releases.
 */
typedef struct {
    char serial_number[32];            /* Vendor optical module serial number */
    char vendor_part_number[32];       /* Model/Part designation (e.g. SFP-10G-LR) */
    TransceiverFormFactor form_factor; /* Form factor enum */
    double wavelength_nm;              /* Optical wavelength (e.g., 850.0, 1310.0, 1550.0 nm) */
    
    /* Dynamic Optical Telemetry (DDM/DOM) */
    double rx_power_dbm;               /* Received Optical Power in dBm (typical: -18 dBm to -3 dBm) */
    double tx_power_dbm;               /* Transmit Optical Power in dBm (typical: -6 dBm to 0 dBm) */
    double laser_bias_current_ma;      /* Laser Diode Forward Bias Current in mA (typical: 20-50 mA) */
    double temperature_c;              /* Internal Transceiver Temperature in Celsius (typical: 20-65 C) */
    double voltage_v;                  /* Internal Transceiver Supply Voltage in Volts (typical: 3.1-3.5 V) */
    
    bool is_simulated;                 /* Explicit indicator that metrics are synthetic */
} Transceiver;

/**
 * Initializes a Transceiver structure with default baseline values.
 */
void transceiver_init(Transceiver *xcvr, const char *serial, const char *part_no, 
                     TransceiverFormFactor form_factor, double wavelength_nm);

/**
 * Synthesizes optical telemetry values according to a simulation scenario profile.
 *
 * @param xcvr Target transceiver structure.
 * @param scenario Scenario profile (NORMAL, WARNING, CRITICAL, FAULT_SPIKE).
 */
void transceiver_simulate_telemetry(Transceiver *xcvr, ScenarioType scenario);

/**
 * Telemetry collector interface for optical modules.
 * Reads DDM telemetry either from simulation or hardware backend.
 *
 * @param xcvr Target transceiver structure.
 * @param bus_or_interface I2C bus path or network interface name.
 * @param simulate If true, synthetically generates optical metrics.
 * @return 0 on success, negative error code on failure.
 */
int transceiver_collect_telemetry(Transceiver *xcvr, const char *bus_or_interface, bool simulate);

/**
 * Converts a TransceiverFormFactor to a human-readable string.
 */
const char *transceiver_form_factor_to_string(TransceiverFormFactor form_factor);

/**
 * Converts a form factor string to its corresponding enum value.
 */
TransceiverFormFactor transceiver_parse_form_factor(const char *str);

#endif /* NETDIAG_TRANSCEIVER_H */
